TERMS OF SERVICE</br><br>
General</br>
The following are terms of a legal agreement between you and Quantimodo, owned and operated by Quantimodo Inc. By accessing, browsing, or using this Quantimodo World Wide Web Site ("Site"), you acknowledge that you have read, understood, and agree to be bound by these terms of use. If you do not agree to these terms, please do not use this Site.</br>
Copyright and Other Intellectual Property Rights</br>
This Site and all content in this site may not be copied, reproduced, republished, uploaded, posted, transmitted, distributed, or used for the creation of derivative works without Quantimodo's prior written consent (which may be granted, withheld or conditioned in Quantimodo's sole discretion), except that Quantimodo hereby grants you non-exclusive, non-transferable, limited permission to access and display the web pages within this site, solely on your computer and for your personal, non-commercial use of this Site. This permission is conditioned on your not modifying the content displayed on this site, your keeping intact all copyright, trademark, and other proprietary notices, and your acceptance of any terms, conditions, and notices accompanying the content or otherwise set forth in this site. Notwithstanding the foregoing, any software and other materials that are made available for downloading, access, or other use from this site with their own license terms, conditions, and notices will be governed by such terms, conditions, and notices. Any product, process or technology described in this Site may be the subject of other intellectual property rights reserved by Quantimodo. Nothing contained under this Site terms of use shall be construed as conferring by implication, estoppel or otherwise any license or right under any patent, trademark, copyright or other intellectual property right of Quantimodo or any third party. Any rights not expressly granted herein are reserved.</br>
Quantimodo, the Quantimodo logo, and other names of Quantimodo and Quantimodo products referenced in this Site are registered trademarks or other trademarks, service marks or trade names of Quantimodo Inc. or its subsidiaries. No license to use any of these trademarks is given or implied. Quantimodo's trademarks may be used only with prior written permission from Quantimodo, which may be granted, withheld or conditioned in Quantimodo's sole discretion. All other trademarks or trade names referenced on this Site are the property of their respective owners. You may not use contact information provided on this Site for unauthorized purposes, including marketing. You may not use any hardware or software intended to damage or interfere with the proper working of this Site or to surreptitiously intercept any system, data or personal information from the site. You agree not to interrupt or attempt to interrupt the operation of this Site in any way. Your failure to comply with the terms, conditions, and notices on this site will result in automatic termination of any rights granted to you, without prior notice, and you must immediately destroy all copies of downloaded materials in your possession or control. Except for the limited permission granted above with respect to use of this Site, Quantimodo does not grant you any express or implied rights or licenses under any patents, trademarks, copyrights, or other proprietary or intellectual property rights. You may not mirror any of the content from this site on another Site or in any other media.</br>
Information disclaimers/No obligation to update</br>
Information on this Site is not promised or guaranteed to be correct, current, or complete, and this site may be out of date and may contain technical inaccuracies or typographical errors. Any reliance on the material on this site is at your own risk. Quantimodo assumes no responsibility (and expressly disclaims responsibility) for updating this site to keep information current or to ensure the accuracy or completeness of any posted information. Accordingly, you should confirm the accuracy and completeness of all posted information before making any decision related to any services, products, or other matters described in this site.</br>
Material You Submit</br>
Quantimodo does not want to receive confidential or proprietary information from you through our Site. Please note that any information or material sent to Quantimodo will be deemed NOT to be confidential. By sending Quantimodo any information or material, you grant Quantimodo an unrestricted, irrevocable, royalty-free, perpetual license to sublicense, copy, reproduce, publish, upload, post, transmit, distribute, publicly display, perform, modify, create derivative works from, and otherwise freely use, those materials or information anywhere in the world in any media in a non-identifiable manner so as to protect your personal data. You also agree that Quantimodo is free to use any ideas, concepts, know-how, or techniques that you send us for any purpose.</br>
You acknowledge that you are responsible for any material you may submit via this Site, including the legality, reliability, appropriateness, originality and copyright of any such material. You may not upload to, distribute or otherwise publish through this Site any content that (i) is confidential, proprietary, false, fraudulent, libelous, defamatory, obscene, threatening, invasive of privacy or publicity rights, infringing on intellectual property rights, abusive, illegal or otherwise objectionable; (ii) may constitute or encourage a criminal offense, violate the rights of any party or otherwise give rise to liability or violate any law; or (iii) may contain software viruses, political campaigning, chain letters, mass mailings, or any form of "spam." You may not use a false email address or other identifying information, impersonate any person or entity or otherwise mislead as to the origin of any content. You may not upload commercial content onto this Site.</br>
Global availability</br>
Information Quantimodo publishes on the World Wide Web may contain references or cross references to Quantimodo products, programs and services that are not announced or available in your country. Such references do not imply that Quantimodo intends to announce or make available such products, programs, or services in your country. </br>
Non-Quantimodo Links/Sites</br>
This Site may provide links or references to non-Quantimodo web sites and resources. Quantimodo makes no representations, warranties, or other commitments whatsoever about any non-Quantimodo web sites or third-party resources that may be referenced, accessible from, or linked to any Quantimodo web site. A link to a non-Quantimodo web site does not mean that Quantimodo endorses the content or use of such web site or its owner. In addition, Quantimodo is not a party to or responsible for any transactions you may enter into with third parties, even if you learn of such parties (or use a link to such parties) from a Quantimodo web site. Accordingly, you acknowledge and agree that Quantimodo is not responsible for the availability of such external sites or resources, and is not responsible or liable for any content, services, products, or other materials on or available from those sites or resources. When you access a non-Quantimodo web site, even one that may contain the Quantimodo logo, please understand that it is independent from Quantimodo, and that Quantimodo does not control the content on that Web site. It is up to you to take precautions to protect yourself from viruses, worms, trojan horses, and other potentially destructive programs, and to protect your information as you deem appropriate.</br>
Translations</br>
Certain text in this Site may be made available in languages other than English. Text may be translated by a person or solely by computer software with no human intervention or review. These translations are provided as a convenience to you, and Quantimodo makes no representations or commitments regarding the accuracy or completeness of the translation, whether or not computer-generated or performed by a person. Please see the below Disclaimer of Warranty for additional conditions.</br>
DISCLAIMERS</br>
USE OF THIS SITE IS AT YOUR SOLE RISK. THIS SITE AND ALL MATERIALS, INFORMATION, PRODUCTS, SOFTWARE, PROGRAMS, AND SERVICES ARE PROVIDED "AS IS," "AS AVAILABLE" BASIS WITH NO WARRANTIES OR GUARANTEES WHATSOEVER. Quantimodo EXPRESSLY DISCLAIMS TO THE FULLEST EXTENT PERMITTED BY LAW ALL EXPRESS, IMPLIED, STATUTORY, AND OTHER WARRANTIES, GUARANTEES, OR REPRESENTATIONS, INCLUDING, WITHOUT LIMITATION, THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT OF PROPRIETARY AND INTELLECTUAL PROPERTY RIGHTS. WITHOUT LIMITATION, Quantimodo MAKES NO WARRANTY OR GUARANTEE THAT THIS SITE WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE. YOU UNDERSTAND AND AGREE THAT IF YOU DOWNLOAD OR OTHERWISE OBTAIN MATERIALS, INFORMATION, PRODUCTS, SOFTWARE, PROGRAMS, OR SERVICES, YOU DO SO AT YOUR OWN DISCRETION AND RISK AND THAT YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGES THAT MAY RESULT, INCLUDING LOSS OF DATA OR DAMAGE TO YOUR COMPUTER SYSTEM.</br>
LIMITATION OF LIABILITY</br>
YOU ACKNOWLEDGE AND AGREE THAT YOU ASSUME FULL RESPONSIBILITY FOR YOUR USE OF THIS SITE. YOU ACKNOWLEDGE AND AGREE THAT ANY INFORMATION YOU SEND OR RECEIVE DURING YOUR USE OF THIS SITE MAY NOT BE SECURE AND MAY BE INTERCEPTED BY UNAUTHORIZED PARTIES. YOU ACKNOWLEDGE AND AGREE THAT YOUR USE OF THIS SITE IS AT YOUR OWN RISK AND THAT THIS SITE IS MADE AVAILABLE TO YOU AT A LOW FEE. RECOGNIZING SUCH, YOU ACKNOWLEDGE AND AGREE THAT, TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, NEITHER Quantimodo NOR ITS AFFILIATES, SUPPLIERS OR THIRD PARTY CONTENT PROVIDERS WILL BE LIABLE FOR ANY DIRECT, INDIRECT, PUNITIVE, EXEMPLARY, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR OTHER DAMAGES ARISING OUT OF OR IN ANY WAY RELATED TO THIS SITE, OR ANY OTHER SITE YOU ACCESS THROUGH A LINK FROM THIS SITE OR FROM ANY ACTIONS WE TAKE OR FAIL TO TAKE AS A RESULT OF COMMUNICATIONS YOU SEND TO US, OR THE DELAY OR INABILITY TO USE THIS SITE, OR FOR ANY INFORMATION, PRODUCTS OR SERVICES ADVERTISED IN OR OBTAINED THROUGH THIS SITE, Quantimodo'S REMOVAL OR DELETION OF ANY MATERIALS SUBMITTED OR POSTED ON THIS SITE, OR OTHERWISE ARISING OUT OF THE USE OF THE SITE, WHETHER BASED ON CONTRACT, TORT, STRICT LIABILITY OR OTHERWISE, EVEN IF Quantimodo, ITS AFFILIATES OR ANY OF ITS SUPPLIERS HAS BEEN ADVISED OF THE POSSIBILITY OF DAMAGES. THIS DISCLAIMER APPLIES, WITHOUT LIMITATION, TO ANY DAMAGES OR INJURY ARISING FROM ANY FAILURE OF PERFORMANCE, ERROR, OMISSION, INTERRUPTION, DELETION, DEFECTS, DELAY IN OPERATION OR TRANSMISSION, COMPUTER VIRUSES, FILE CORRUPTION, COMMUNICATION-LINE FAILURE, NETWORK OR SYSTEM OUTAGE, YOUR LOSS OF PROFITS, OR THEFT, DESTRUCTION, UNAUTHORIZED ACCESS TO, ALTERATION OF, LOSS OR USE OF ANY RECORD OR DATA, AND ANY OTHER TANGIBLE OR INTANGIBLE LOSS. YOU SPECIFICALLY ACKNOWLEDGE AND AGREE THAT NEITHER Quantimodo NOR ITS SUPPLIERS SHALL BE LIABLE FOR ANY DEFAMATORY, OFFENSIVE OR ILLEGAL CONDUCT OF ANY USER OF THIS SITE. YOUR SOLE AND EXCLUSIVE REMEDY FOR ANY OF THE ABOVE CLAIMS OR ANY DISPUTE WITH Quantimodo IS TO DISCONTINUE YOUR USE OF THE SITE. YOU AND Quantimodo AGREE THAT ANY CAUSE OF ACTION ARISING OUT OF OR RELATED TO THE SITE MUST COMMENCE WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES OR THE CAUSE OF ACTION IS PERMANENTLY BARRED. BECAUSE SOME JURISDICTIONS DO NOT ALLOW LIMITATIONS ON HOW LONG AN IMPLIED WARRANTY LASTS, OR THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, ALL OR A PORTION OF THE ABOVE LIMITATION MAY NOT APPLY TO YOU.</br>
Indemnification</br>
You agree to indemnify, defend and hold harmless Quantimodo and its affiliates and their officers, directors, employees, contractors, agents, licensors, service providers, subcontractors and suppliers from and against any and all losses, liabilities, expenses, damages and costs, including reasonable attorneys' fees and court costs, arising or resulting from your use of the site and any violation of these Terms of Use. If you cause a technical disruption of the site or the systems transmitting the site to you or others, you agree to be responsible for any and all losses, liabilities, expenses, damages and costs, including reasonable attorneys' fees and court costs, arising or resulting from that disruption. Quantimodo reserves the right, at its own expense, to assume exclusive defense and control of any matter otherwise subject to indemnification by you and, in such case, you agree to cooperate with Quantimodo in the defense of such matter.</br>
Jurisdiction</br>
This Site is controlled and operated by Quantimodo from its offices within Tokyo, Japan. These terms of use shall be governed by and construed in accordance with the laws of Japan, without giving effect to any principles of conflicts of law. You agree that any action at law or in equity arising out of or relating to these terms shall be filed only in the state or federal courts located in Tokyo, Japan and you hereby consent and submit to the personal jurisdiction of such courts for the purposes of litigating any such action.</br>
Applicable laws</br>
This Site is controlled by Quantimodo from its offices within Japan. Quantimodo makes no representation that materials and information in the Site are appropriate or available for use in other locations, and access to them from territories where their content is illegal is prohibited. Those who choose to access this Site from other locations do so on their own initiative and are responsible for compliance with applicable local laws. You may not use or export the materials or information posted on this Site in violation of Japanese export laws and regulations.</br>
cancellations</br>
You can always cancel your annual subscription by deleting your account. You will not be charged again and we will delete all your data. Of course, you are able to export and save all your data on your local computer before deleting your account.</br>
refunds</br>
We do not pay refunds or damages for any reason at all. The annual subscription fee is very low and can be cancelled at any time. No refund will be given for the remainder of the year. All subscription fees are symbolic contributions to the development and maintenance of the website without any promise of service continuity or availability of data.</br>
backup</br>
Each Quantimodo member should download all personal application data with the tools provided and store it on a local computer for personal backup. Quantimodo is a useful tool of which the infinite continuity of business cannot be promised or foreseen. Quantimodo is not responsible for eternal backup of data and does not guarantee data completeness. Quantimodo is not able to retrieve your data after you have deleted your account, even if this would be by accident.</br>
Modification of terms of use</br>
Quantimodo may, without notice to you, revise these terms of use and any other information contained in this site at any time by changing, adding to, deleting from or otherwise updating this posting. You should visit this Site from time to time to review the then-current terms or use because they are binding on you. Certain provisions of these terms of use may be superseded by expressly designated legal notices or terms located on particular pages at this Site. You agree that your accessing and using this Site is the functional equivalent of your signature and you hereby waive any objection to electronic assent to this agreement, whether based on the Statute of Frauds or similar law, rule, or regulation. A printed version of these Terms of Use shall be admissible in judicial or administrative proceedings based on or relating to use of this site to the same extent and subject to the same conditions as other business documents and records originally generated and maintained in printed form. If any provision of these terms of use shall be unlawful or any reason unenforceable, then that provision shall be deemed severable from these terms and shall not affect the validity and enforceability of any remaining provisions.</br>
Copyright (c) 2012 Quantimodo Inc. All rights reserved.</br>
 </br>
 PP</br>
</br>
Privacy Policy</br>
 </br>
This privacy policy was last updated on 9/12/2012</br>
</br>
To obtain a copy of this policy email info@Quantimodo.com</br>
 </br>
Users of this website are also bound by the terms of Use (LINK)</br>
 </br>
Scope Of Privacy Policy</br>
 </br>
This Privacy Policy applies to your use of all the sites and services owned or operated by Quantimodo INC (collectively "we," "us," or "our"), including Quantimodo.com, and any other site that we may own or operate currently or in the future (collectively, the "Website" or "Websites"). Unless specifically stated otherwise, all references to the Websites in this policy include all such sites. This policy does not apply to your use of sites to which any of the Website may link to (“3rd party websites”). This policy covers only information collected on the Website, and does not cover any information collected by third 3rd party websites.</br>
 </br>
Your privacy is very important to us. We have developed this Policy in order for you to understand how we collect, use, communicate and disclose and make use of personal information. We will collect and use of personal information solely with the objective of fulfilling those purposes specified by us and for other compatible purposes, unless we obtain the consent of the individual concerned or as required by law.</br>
 </br>
We will make readily available to customers information about our policies and practices relating to the management of personal information. We are committed to conducting our business in accordance with these principles in order to ensure that the confidentiality of personal information is protected and maintained.</br>
 </br>
 Quantimodo.com is not responsible for the privacy statements or other content on websites outside of the Website and the Quantimodo.com family of websites.</br>
 </br>
Children Under Thirteen</br>
Quantimodo.com is not directed to children under the age of thirteen, but we understand that with adult supervision, some parents may choose to permit their children to visit our Website.  Quantimodo.com will never knowingly collect personally identifiable information from children under the age of thirteen. If you are under the age of thirteen, please do not visit Quantimodo.com</br>
 </br>
Information Sharing and Disclosure.</br>
When you register through the Site and Applications and submit Personal Information to create a profile or visual collection, Quantimodo Users may see your name. If you choose to provide additional Personal Information in your profile, Quantimodo Users may see such additional Personal Information, including, but not limited to, your photo, location, website and biography. Providing additional Personal Information is voluntary and should correlate with the degree of interaction you want to have with Quantimodo Users. We recommend that you guard your sensitive information.</br>
 </br>
Service Providers.</br>
We may employ third party companies and individuals to facilitate our Service, to provide the Service on our behalf, to perform Site and Application-related services (e.g., without limitation, maintenance services, database management, web analytics and improvement of the Site and Application’s features) or to assist us in analyzing how our Site, Applications and Service are used. These third parties have access to your Personal Information only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</br>
 </br>
Compliance with Laws and Law Enforcement.</br>
Quantimodo INC may cooperate with government and law enforcement officials and private parties to enforce and comply with the law. We may disclose any information about you to government or law enforcement officials or private parties as we believe necessary or appropriate to respond to claims and legal process (including, but not limited to, subpoenas), to protect the property and rights of Quantimodo, another third party, to protect the safety of the public or any person, or to prevent or stop activity we may consider to be, or to pose a risk of being, illegal, unethical or legally actionable activity.</br>
We will release information about you to comply with any valid legal inquiry or process such as a court order, search warrant, subpoena, statute of which We are compelled by law. In the event that Quantimodo.com goes through a business transaction, such as a merger or acquisition, your personally identifiable information will most likely be among the assets transferred. You will be notified via email of any such change in ownership or control of your personal information.</br>
Personally Identifiable Information</br>
With your permission, we may use personal identification information for internal or external marketing and/or promotional purposes. We may send you e-mails to present a product or a service.</br>
 </br>
The information you enter when making a purchase of a product or service will be transferred and shared via a secure SSL connection with payment processors, and your credit card company who will authorize credit card payments. This information may also be shared with other necessary third parties, but only for the purpose or carrying out the transactions for the products or services you have ordered.</br>
 </br>
Non-Personal Identifiable Information</br>
We collect non-personal identification information through the use of cookies. The Quantimodo.com website may sometimes use "cookies" to personalize your online experience. The purpose of a cookie is to tell the Web server that you have returned to a specific page. Cookies cannot run programs or deliver viruses to your computer. You have the ability to accept or decline cookies by altering the settings in your web browser.</br>
 </br>
You have the ability to accept or decline cookies. Most Web browsers automatically accept cookies, but you can usually modify your browser setting to decline cookies if you prefer. If you choose to decline cookies, you may not be able to fully experience the interactive features of the Quantimodo.com services or Website</br>
 </br>
We use non-personal identifiable information to better manage advertising on the Sites, and to understand how our users as a group use the Website services. This way we know which areas of our Sites are favorites of our users, which areas need improvement, and what technologies are being used so that we may continually improve our Sites.</br>
 </br>
Personal Information Security</br>
Quantimodo.com secures the personally identifiable information you provide on computer servers in a secure environment. Your information is always protected from unauthorized access. If personal information (such as a credit card number) is transmitted to other websites, its transmission is protected through the use of encryption, such as Secure Socket Layer (SSL) protection.</br>
 </br>
Business Transfers</br>
Quantimodo INC may sell, transfer or otherwise share some or all of its assets, including your Personal Information, in connection with a merger, acquisition, reorganization or sale of assets or in the event of bankruptcy.</br>
 </br>
Quantimodo.com keeps track of the websites and pages our customers visit within Website, in order to determine what Website services are the most popular. This data is used to deliver customized content and advertising within Website to customers whose behavior indicates that they are interested in a particular subject area.</br>
 </br>
Quantimodo.com websites will disclose your personal information, without notice, only if required to do so by law or in the good faith belief that such action is necessary to: (a) conform to the edicts of the law or comply with legal process served on Website or the site; (b) protect and defend the rights or property of Quantimodo.com; and, (c) act under exigent circumstances to protect the personal safety of users of Website, or the public.</br>
 </br>
If you have any questions or comments about our Privacy Policy, or to receive a copy, please e-mail us at info@Quantimodo.com</br>
 </br>
 </br>
 </br>
</br>
</br>

